version: '3'

services:
  stefan-springboot-container:
    image: stefan-spring-boot-docker-compose:1
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - /data/stefan-springboot-container
    ports:
      - "8080-8100:8888"
