apiVersion: apps/v1
kind: Deployment
metadata:
  name: stefan-springboot
spec:
  replicas: 3
  selector:
    matchLabels:
      app: stefan-springboot
  template:
    metadata:
      labels:
        app: stefan-springboot
    spec:
      containers:
        - name: springboot
          image: muchast2/stefan-docker-demo:latest
          ports:
            - containerPort: 8888
          env:
            - name: PORT
              value: "8888"
---
apiVersion: v1
kind: Service
metadata:
  name: stefan-springboot
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8888
  selector:
    app: stefan-springboot
